version: 2
run:
  timeout: 5m
  tests: true
  allow-parallel-runners: true
  modules-download-mode: readonly

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-dirs: [deploy, docs, scripts, migrations]
  exclude:
    - "error return value not checked.*(Close|Log|Print).*(errcheck)"
  exclude-rules:
    - path: _test\.go
      linters: [cyclop, funlen, gosec, dupl]

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - ineffassign
    - revive
    - gocritic
    - misspell
    - prealloc
    - cyclop
  disable: [dupl]

linters-settings:
  misspell:
    locale: US
  cyclop:
    max-complexity: 12
    skip-tests: true
  revive:
    rules:
      - name: exported
        disabled: true
      - name: if-return
      - name: increment-decrement
      - name: range-val-in-closure
      - name: redefines-builtin-id
      - name: superfluous-else
      - name: unused-parameter
      - name: unreachable-code
